name: Run prover guest code checks

on:
  pull_request:
  merge_group:
  push:
    branches: [main]

jobs:
  eval_perf:
    permissions: write-all
      # Needed to install the toolchain.
      #contents: write-all
      # Needed to post the performance report comments.
      #pull-requests: write
      #issues: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2024-07-27

      - name: Cleanup space
        uses: ./.github/actions/cleanup # zizmor: ignore[unpinned-uses]
      - name: Install toolchains
        uses: ./.github/actions/toolchains # zizmor: ignore[unpinned-uses]

      - name: Use Cargo cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      # Installs mold (modern ld), a drop-in replacement for lld.
      # Under the hood, the following action symlinks mold binary onto lld,
      # so everything is linked faster (hopefully).
      - name: Install mold linker
        uses: rui314/setup-mold@v1

      - name: Run performance evaluation
        run: |
          cargo run --release -- \
          --post-to-gh \
          --github-token "${{ secrets.GITHUB_TOKEN }}" \
          --pr-number "${{ github.event.pull_request.number }}" \
          --commit-hash "${{ github.sha }}" \
        working-directory: perf
        env:
          RUSTFLAGS: "-C target-cpu=native -C link-arg=-fuse-ld=lld"

